name = "personal-inteligente"
type = "javascript"

account_id = "e1057b9d90ac5608b750b856533975eaac23f"
workers_dev = true

[build]
command = "npm run build"
upload.format = "directory"  # Alterado de "service-worker" para "directory"
pages_build_output_dir = "build"  # Certifique-se de que este diretório existe após o build

[env.production]
name = "personal-inteligente-prod"
workers_dev = true
